### ISSUE TITLE
Select doesn't use default option with selected attribute

### ISSUE THREAD

**Issue by freudFlintstone** [mobily-enterprises/tpe#4]
In select boxes, it's common to use a first option set with attributes 'disabled' and 'select' to show a placeholder option at first. This does not work in nn-select

**Comment by mercmobily** [comment]
What do you mean by "doesn't work"?
What does native do _exactly_, and what do nn- ones do instead?

**Comment by freudFlintstone** [comment]
It's not that. It was actually work perfectly. But because I used name="name" it was receiving the value 'a' from the server. Today, I have a server problem and select shows, correctly, the empty first option before interaction

**Comment by mercmobily** [comment]
Hi,

So, this is not a bug?

Merc.
