### ISSUE TITLE
Focus on input fields

### ISSUE THREAD

**Issue by mercmobily** [mobily-enterprises/tpe#6]
This is a minor thing, but it will irk people...
Imagine you have this:

![image](https://user-images.githubusercontent.com/2128734/65363512-e2a41d00-dc3e-11e9-8682-8014cc93a415.png)

Is it possible to get the focus on the input field even if you click on the error message?
The error message takes up "clickable space" in terms of giving the text element focus

**Comment by freudFlintstone** [comment]
after the revised styling, in line with Material guidelines, it's not a problem anymore.
